export const CHARACTER_LIST_FETCHED = "CHARACTER_LIST_FETCHED";
export const CHARACTER_COUNT_FETCHED = "CHARACTER_COUNT_FETCHED";
export const WORLD_FETCHED = "WORLD_FETCHED";
export const FILM_FETCHED = "FILM_FETCHED";